Extension { #name : #Object }

{ #category : #'*Ml4St' }
Object >> isMlArray [	
	^ false
]

{ #category : #'*Ml4St' }
Object >> isMlBufferedArray [
	^ false
]

{ #category : #'*Ml4St' }
Object >> isMlFloatArray [
	^ false
]

{ #category : #'*Ml4St' }
Object >> isMlIntArray [
	^ false
]

{ #category : #'*Ml4St' }
Object >> isMlInterval [

	^ false
]

{ #category : #'*Ml4St' }
Object >> isMlTreeNode [
	^ false
]

{ #category : #'*Ml4St' }
Object >> isNonContinuousVector [
	^ false
]

{ #category : #'*Ml4St' }
Object >> isSlice [ 	
	^ false
]

{ #category : #'*Ml4St' }
Object >> supportsNativeSlicing [
	^ false
]
